# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: en/about
    weight: 100
  - name: Topics
    url: tags/
    weight: 200
  - name: Uses
    url: uses/
    weight: 300
