# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: about/
    weight: 100
  - parent: About
    name: Profile
    url: about/
    weight: 110
  - parent: About
    name: etc.
    url: skills/
    weight: 120

  - name: Topics
    url: tags/
    weight: 200
  - name: Uses
    url: uses/
    weight: 300
