# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: Minimal
  theme_night: dark
  font: Cyberpunk 
  font_size: L
  color: green


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '전북대학교'
    description: '전북대학교 컴퓨터인공지능학부 최현솔입니다'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '전북대학교 최현솔'
    pinterest: '전북대학교 최현솔'

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true
    align: center
    logo:
      text: "Hyunsol's Portpolio"

# Site footer
footer:
  copyright:
    notice: '© {year} Hyunsol. With WSD'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main
